name: Deploy API to AWS

on:
    push:
        branches:
            - main
        paths:
            - 'modules/api/**'
            - 'modules/aws/**'
            - 'modules/utils/**'
            - '.github/workflows/deploy-api.yml'
    workflow_dispatch:
        inputs:
            target:
                description: 'Target environment'
                required: true
                default: 'dev'
                type: choice
                options:
                    - 'dev'
                    - 'prod'

env:
    AWS_REGION: 'eu-west-1'

jobs:
    deploy:
        name: Deploy to ${{ inputs.target || 'dev' }} environment
        runs-on: ubuntu-latest
        environment: ${{ inputs.target || 'dev' }}
        concurrency: api-${{ inputs.target || 'dev' }}-deployment
        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Install dependencies
              run: yarn install

            - name: Run tests
              run: yarn test --ci --passWithNoTests modules/api

            - name: Deploy api stack
              working-directory: modules/api
              run: yarn cdk deploy --all --require-approval never
              env:
                  ENVIRONMENT: ${{ inputs.target || 'dev' }}
