name: Pull Request Client

on:
    pull_request:
        branches:
            - main
        paths:
            - 'modules/client/**'
            - 'modules/infrastructure/**'
            - 'modules/utils/**'
            - '.github/workflows/pr-frontend.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4

            - name: Install dependencies
              run: yarn install

            - name: Run ESlint
              run: yarn run eslint ./modules/client/

            - name: Run Prettier
              run: yarn prettier

            - name: Run tests
              run: yarn test --ci --passWithNoTests modules/client

            - name: Build
              run: yarn workspace @monorepo/client build
